[package]
name = "resource_monitor"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/monitor_panel.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
context_bus.workspace = true
gpui.workspace = true
log.workspace = true
panel.workspace = true
regex.workspace = true
serde.workspace = true
ui.workspace = true
workspace.workspace = true
